[window]
padding = { x = 6, y = 4 }
dimensions = { columns = 160, lines = 35 }

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 10
builtin_box_drawing = false

[colors]
primary.background = "#1f1f1f"

[cursor]
style = { shape = "Block", blinking = "Off" }
